services:
  - type: web
    name: odoo
    runtime: image
    image:
      url: odoo:16.0
    plan: free
    healthCheckPath: /web/login
    envVars:
      - key: HOST
        fromDatabase:
          name: odoo-db
          property: host
      - key: PORT
        value: 5432
      - key: USER
        fromDatabase:
          name: odoo-db
          property: user
      - key: PASSWORD
        fromDatabase:
          name: odoo-db
          property: password
      - key: DB_NAME
        value: odoo
    disks:
      - name: odoo-data
        mountPath: /var/lib/odoo
        sizeGB: 1

databases:
  - name: odoo-db
    plan: free
    databaseName: odoo
